-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aluno
(
    id uuid NOT NULL,
    cpf character varying(14) COLLATE pg_catalog."default",
    rg character varying(20) COLLATE pg_catalog."default",
    endereco character varying(255) COLLATE pg_catalog."default",
    instituicao_id uuid,
    curso character varying(100) COLLATE pg_catalog."default",
    saldo_moedas double precision NOT NULL DEFAULT 0.0,
    CONSTRAINT aluno_pkey PRIMARY KEY (id),
    CONSTRAINT aluno_cpf_key UNIQUE (cpf)
);

CREATE TABLE IF NOT EXISTS public.instituicao
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    endereco character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT instituicao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.professor
(
    id uuid NOT NULL,
    cpf character varying(14) COLLATE pg_catalog."default",
    departamento character varying(100) COLLATE pg_catalog."default",
    quantidade_moedas double precision NOT NULL DEFAULT 1000,
    instituicao_id uuid,
    CONSTRAINT professor_pkey PRIMARY KEY (id),
    CONSTRAINT professor_cpf_key UNIQUE (cpf)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    id uuid NOT NULL,
    cnpj character varying(18) COLLATE pg_catalog."default",
    CONSTRAINT empresa_pkey PRIMARY KEY (id),
    CONSTRAINT empresa_cnpj_key UNIQUE (cnpj)
);

CREATE TABLE IF NOT EXISTS public.vantagem
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    titulo character varying(255) COLLATE pg_catalog."default",
    descricao text COLLATE pg_catalog."default",
    imagem character varying(255) COLLATE pg_catalog."default",
    custo_moedas integer,
    empresa_id uuid NOT NULL,
    CONSTRAINT vantagem_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cupom
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    codigo varchar(10) NOT NULL,
    data_geracao timestamptz NOT NULL DEFAULT now(),
    aluno_id uuid NOT NULL,
    vantagem_id uuid NOT NULL,
    CONSTRAINT cupom_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transacao
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    valor double precision NOT NULL,
    descricao text COLLATE pg_catalog."default" NOT NULL,
    remetente_id uuid NOT NULL,
    destinatario_id uuid NOT NULL,
    data_transacao timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT transacao_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT aluno_instituicao_id_fkey FOREIGN KEY (instituicao_id)
    REFERENCES public.instituicao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_usuario FOREIGN KEY (id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS aluno_pkey
    ON public.aluno(id);


ALTER TABLE IF EXISTS public.professor
    ADD CONSTRAINT fk_professor_usuario FOREIGN KEY (id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS professor_pkey
    ON public.professor(id);


ALTER TABLE IF EXISTS public.professor
    ADD CONSTRAINT professor_instituicao_id_fkey FOREIGN KEY (instituicao_id)
    REFERENCES public.instituicao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT fk_empresa_usuario FOREIGN KEY (id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS empresa_pkey
    ON public.empresa(id);


ALTER TABLE IF EXISTS public.vantagem
    ADD CONSTRAINT vantagem_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cupom
    ADD CONSTRAINT cupom_aluno_id_fkey FOREIGN KEY (aluno_id)
    REFERENCES public.aluno (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cupom
    ADD CONSTRAINT cupom_vantagem_id_fkey FOREIGN KEY (vantagem_id)
    REFERENCES public.vantagem (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transacao
    ADD CONSTRAINT transacao_destinatario_id_fkey FOREIGN KEY (destinatario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.transacao
    ADD CONSTRAINT transacao_remetente_id_fkey FOREIGN KEY (remetente_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;